// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioFormController from "./audio_form_controller"
application.register("audio-form", AudioFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)
